import SystemE
import Book1.Prop30.step7_othercases_opp
import Book1.Prop30.step7_othercases_c2_ang1
import Book1.Prop30.step7_othercases_c2_ang2
import Book1.Prop30.step7_othercases_c2_ang
import Book1.Prop30.step7_othercases_c2
import Book1.Prop30.step7_othercases_c3_ang1
import Book1.Prop30.step7_othercases_c3_ang2
import Book1.Prop30.step7_othercases_c3_ang
import Book1.Prop30.step7_othercases_c3
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace Elements.Book1

theorem helper_1_30_step7_othercases
    (AB CD EF GK : Line) (a b c d e f g h k : Point)
    (hg_AB : g.onLine AB) (ha_AB : a.onLine AB) (hb_AB : b.onLine AB)
    (hk_CD : k.onLine CD) (hc_CD : c.onLine CD) (hd_CD : d.onLine CD)
    (hh_EF : h.onLine EF) (he_EF : e.onLine EF) (hf_EF : f.onLine EF)
    (hg_GK : g.onLine GK) (hh_GK : h.onLine GK) (hk_GK : k.onLine GK)
    (hbetw_agb : between a g b)
    (hbetw_ehf : between e h f)
    (hbetw_ckd : between c k d)
    (heside : e.sameSide a GK)
    (hcside : c.sameSide a GK)
    (hnopar_AB : ¬AB.intersectsLine EF)
    (hnopar_CD : ¬CD.intersectsLine EF)
    (hnot_ghk : ¬between g h k)
    (hgk : g ≠ k)
    (hCDneEF : CD ≠ EF)
    (hEFneAB : EF ≠ AB)
    : ¬(AB.intersectsLine CD) := by
  by_cases hc2 : between g k h
  ·
    have step7_othercases_opp : a.opposingSides d GK := by euclid_apply (helper_1_30_step7_othercases_opp GK a c d k (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show c.sameSide a GK; assumption)) (by euclid_assumption "" (show between c k d; assumption)))
    have step7_othercases_c2_ang1 : ∠ a:g:h = ∠ g:h:f := by euclid_apply (helper_1_30_step7_othercases_c2_ang1 AB EF GK a b e f g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show between g k h; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine EF; assumption)))
    have step7_othercases_c2_ang2 : ∠ g:k:d = ∠ k:h:f := by euclid_apply (helper_1_30_step7_othercases_c2_ang2 EF CD GK a c d e f g h k (by euclid_assumption "" (show k.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show between c k d; assumption)) (by euclid_assumption "" (show between g k h; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show c.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬CD.intersectsLine EF; assumption)))
    have step7_othercases_c2_ang : ∠ a:g:k = ∠ g:k:d := by euclid_apply (helper_1_30_step7_othercases_c2_ang AB EF GK a b d e f g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show between g k h; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine EF; assumption)) (by euclid_assumption "" (show ∠ a:g:h = ∠ g:h:f; assumption)) (by euclid_assumption "" (show ∠ g:k:d = ∠ k:h:f; assumption)))
    have step7_othercases_c2 : ¬(AB.intersectsLine CD) := by euclid_apply (helper_1_30_step7_othercases_c2 AB CD GK a b c d g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show k.onLine CD; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between c k d; assumption)) (by euclid_assumption "" (show between g k h; assumption)) (by euclid_assumption "" (show ∠ a:g:k = ∠ g:k:d; assumption)) (by euclid_assumption "" (show a.opposingSides d GK; assumption)))
    exact step7_othercases_c2
  ·
    have hkh : k ≠ h := by euclid_finish
    have hgh : g ≠ h := by euclid_finish
    have step7_othercases_opp : a.opposingSides d GK := by euclid_apply (helper_1_30_step7_othercases_opp GK a c d k (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show c.sameSide a GK; assumption)) (by euclid_assumption "" (show between c k d; assumption)))
    have step7_othercases_c3_ang1 : ∠ d:k:h = ∠ k:h:e := by euclid_apply (helper_1_30_step7_othercases_c3_ang1 EF CD GK a c d e f g h k (by euclid_assumption "" (show k.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show between c k d; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show c.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬CD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬between g h k; assumption)) (by euclid_assumption "" (show ¬between g k h; assumption)) (by euclid_assumption "" (show k ≠ h; assumption)))
    have step7_othercases_c3_ang2 : ∠ k:g:a = ∠ g:h:e := by euclid_apply (helper_1_30_step7_othercases_c3_ang2 AB EF GK a b e f g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬between g h k; assumption)) (by euclid_assumption "" (show ¬between g k h; assumption)) (by euclid_assumption "" (show g ≠ k; assumption)) (by euclid_assumption "" (show k ≠ h; assumption)) (by euclid_assumption "" (show g ≠ h; assumption)))
    have step7_othercases_c3_ang : ∠ a:g:k = ∠ g:k:d := by euclid_apply (helper_1_30_step7_othercases_c3_ang AB CD EF GK a b c d e f g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show k.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show h.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between e h f; assumption)) (by euclid_assumption "" (show between c k d; assumption)) (by euclid_assumption "" (show e.sameSide a GK; assumption)) (by euclid_assumption "" (show c.sameSide a GK; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬CD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬between g h k; assumption)) (by euclid_assumption "" (show ¬between g k h; assumption)) (by euclid_assumption "" (show g ≠ k; assumption)) (by euclid_assumption "" (show k ≠ h; assumption)) (by euclid_assumption "" (show g ≠ h; assumption)) (by euclid_assumption "" (show ∠ d:k:h = ∠ k:h:e; assumption)) (by euclid_assumption "" (show ∠ k:g:a = ∠ g:h:e; assumption)))
    have step7_othercases_c3 : ¬(AB.intersectsLine CD) := by euclid_apply (helper_1_30_step7_othercases_c3 AB CD GK a b c d g h k (by euclid_assumption "" (show g.onLine AB; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show k.onLine CD; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show g.onLine GK; assumption)) (by euclid_assumption "" (show h.onLine GK; assumption)) (by euclid_assumption "" (show k.onLine GK; assumption)) (by euclid_assumption "" (show between a g b; assumption)) (by euclid_assumption "" (show between c k d; assumption)) (by euclid_assumption "" (show ¬between g h k; assumption)) (by euclid_assumption "" (show ¬between g k h; assumption)) (by euclid_assumption "" (show g ≠ k; assumption)) (by euclid_assumption "" (show ∠ a:g:k = ∠ g:k:d; assumption)) (by euclid_assumption "" (show a.opposingSides d GK; assumption)))
    exact step7_othercases_c3

end Elements.Book1
