import SystemE
import Mathlib.Tactic.Linarith
import Book1.Prop43.step6_betw_akc
import Book1.Prop43.step6_betw_dfc
import Book1.Prop43.step6_betw_bgc
import Book1.Prop43.step6_betw_aeb
import Book1.Prop43.step6_d_side_par
import Book1.Prop43.step6_b_side_par
import Book1.Prop43.step6_d_side
import Book1.Prop43.step6_b_side
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace Elements.Book1

theorem helper_1_43_step6
    (a b c d e f g h k : Point) (AD BC AB CD AC EF GH : Line)
    (h_a_AD : a.onLine AD) (h_d_AD : d.onLine AD) (h_h_AD : h.onLine AD)
    (h_b_BC : b.onLine BC) (h_c_BC : c.onLine BC) (h_g_BC : g.onLine BC)
    (h_a_AB : a.onLine AB) (h_b_AB : b.onLine AB) (h_e_AB : e.onLine AB)
    (h_d_CD : d.onLine CD) (h_c_CD : c.onLine CD) (h_f_CD : f.onLine CD)
    (h_a_AC : a.onLine AC) (h_c_AC : c.onLine AC) (h_k_AC : k.onLine AC)
    (h_e_EF : e.onLine EF) (h_k_EF : k.onLine EF) (h_f_EF : f.onLine EF)
    (h_h_GH : h.onLine GH) (h_k_GH : k.onLine GH) (h_g_GH : g.onLine GH)
    (h_dc : d ≠ c) (h_ac : a ≠ c) (h_hk : h ≠ k) (h_fc : f ≠ c)
    (h_sameSide_abCD : a.sameSide b CD)
    (h_sameSide_aeGH : a.sameSide e GH)
    (h_sameSide_kgCD : k.sameSide g CD)
    (h_par_AD_BC : ¬AD.intersectsLine BC) (h_par_AB_CD : ¬AB.intersectsLine CD)
    (h_par_AD_EF : ¬AD.intersectsLine EF) (h_par_AB_GH : ¬AB.intersectsLine GH)
    (h_par_EF_BC : ¬EF.intersectsLine BC) (h_par_GH_CD : ¬GH.intersectsLine CD)
    (h_betw_ahd : between a h d)
    (step4 : Triangle.area △ a:e:k + Triangle.area △ k:g:c =
             Triangle.area △ a:h:k + Triangle.area △ k:f:c)
    (step5 : Triangle.area △ a:b:c = Triangle.area △ a:d:c) :
    Triangle.area △ e:b:g + Triangle.area △ e:g:k =
    Triangle.area △ h:k:f + Triangle.area △ h:f:d := by
  have step6_betw_akc : between a k c := by euclid_apply (helper_1_43_step6_betw_akc a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_betw_dfc : between d f c := by euclid_apply (helper_1_43_step6_betw_dfc a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_betw_bgc : between b g c := by euclid_apply (helper_1_43_step6_betw_bgc a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_betw_aeb : between a e b := by euclid_apply (helper_1_43_step6_betw_aeb a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_d_side_par : formParallelogram h d k f AD EF GH CD := by euclid_apply (helper_1_43_step6_d_side_par a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_b_side_par : formParallelogram e b k g AB GH EF BC := by euclid_apply (helper_1_43_step6_b_side_par a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)))
  have step6_d_side : Triangle.area △ a:h:k + Triangle.area △ k:f:c +
                      Triangle.area △ h:k:f + Triangle.area △ h:f:d =
                      Triangle.area △ a:d:c := by euclid_apply (helper_1_43_step6_d_side a c d e f h k AD EF GH CD AC AB (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show h.onLine AD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a h d; assumption)) (by euclid_assumption "" (show between a k c; assumption)) (by euclid_assumption "" (show between d f c; assumption)) (by euclid_assumption "" (show formParallelogram h d k f AD EF GH CD; assumption)))
  have step6_b_side : Triangle.area △ a:e:k + Triangle.area △ k:g:c +
                      Triangle.area △ e:b:g + Triangle.area △ e:g:k =
                      Triangle.area △ a:b:c := by euclid_apply (helper_1_43_step6_b_side a b c e g h k AB GH EF BC AC AD CD (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show between a k c; assumption)) (by euclid_assumption "" (show between b g c; assumption)) (by euclid_assumption "" (show between a e b; assumption)) (by euclid_assumption "" (show formParallelogram e b k g AB GH EF BC; assumption)))
  linarith

end Elements.Book1
