import SystemE
import Book1.Prop43.step6_left
import Book1.Prop43.step6_right
import Book1.Prop43.step6_Ld
import Book1.Prop43.step6_Rd
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace Elements.Book1

theorem helper_1_43_step6
  (a b c d e f g h k : Point) (AD BC AB CD AC EF GH : Line)
  (h_a_AD : a.onLine AD) (h_d_AD : d.onLine AD)
  (h_b_BC : b.onLine BC) (h_c_BC : c.onLine BC)
  (h_a_AB : a.onLine AB) (h_b_AB : b.onLine AB)
  (h_d_CD : d.onLine CD) (h_c_CD : c.onLine CD) (h_dc : d ≠ c)
  (h_ab_ss_CD : a.sameSide b CD)
  (h_AD_BC : ¬AD.intersectsLine BC) (h_AB_CD : ¬AB.intersectsLine CD)
  (h_a_AC : a.onLine AC) (h_c_AC : c.onLine AC) (h_ac : a ≠ c)
  (h_k_AC : k.onLine AC)
  (h_ahd : between a h d)
  (h_e_EF : e.onLine EF) (h_k_EF : k.onLine EF)
  (h_e_AB : e.onLine AB)
  (h_h_GH : h.onLine GH) (h_k_GH : k.onLine GH) (h_hk : h ≠ k)
  (h_ae_ss_GH : a.sameSide e GH)
  (h_AD_EF : ¬AD.intersectsLine EF) (h_AB_GH : ¬AB.intersectsLine GH)
  (h_f_EF : f.onLine EF)
  (h_g_BC : g.onLine BC) (h_g_GH : g.onLine GH)
  (h_f_CD : f.onLine CD) (h_fc : f ≠ c)
  (h_kg_ss_CD : k.sameSide g CD)
  (h_EF_BC : ¬EF.intersectsLine BC) (h_GH_CD : ¬GH.intersectsLine CD)
  (step4 : Triangle.area △ a:e:k + Triangle.area △ k:g:c = Triangle.area △ a:h:k + Triangle.area △ k:f:c)
  (step5 : Triangle.area △ a:b:c = Triangle.area △ a:d:c)
  : Triangle.area △ e:b:g + Triangle.area △ e:g:k = Triangle.area △ h:k:f + Triangle.area △ h:f:d := by
  -- ABC split by k (on AC), e (on AB), g (on BC) into the 4 tiles
  have step6_left : Triangle.area △ a:b:c
      = Triangle.area △ a:e:k + Triangle.area △ k:e:b + Triangle.area △ b:g:k + Triangle.area △ k:g:c := by euclid_apply (helper_1_43_step6_left a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show between a h d; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)))
  -- ADC split by k (on AC), h (on AD), f (on CD) into the 4 tiles
  have step6_right : Triangle.area △ a:d:c
      = Triangle.area △ a:h:k + Triangle.area △ k:h:d + Triangle.area △ d:f:k + Triangle.area △ k:f:c := by euclid_apply (helper_1_43_step6_right a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show between a h d; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)))
  -- complement BK (parallelogram e b g k) — the two diagonal splits are equal
  have step6_Ld : Triangle.area △ e:k:g + Triangle.area △ e:g:b
      = Triangle.area △ b:e:k + Triangle.area △ b:k:g := by euclid_apply (helper_1_43_step6_Ld a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show between a h d; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)))
  -- complement KD (parallelogram h d f k) — the two diagonal splits are equal
  have step6_Rd : Triangle.area △ h:k:f + Triangle.area △ h:f:d
      = Triangle.area △ d:h:k + Triangle.area △ d:k:f := by euclid_apply (helper_1_43_step6_Rd a b c d e f g h k AD BC AB CD AC EF GH (by euclid_assumption "" (show a.onLine AD; assumption)) (by euclid_assumption "" (show d.onLine AD; assumption)) (by euclid_assumption "" (show b.onLine BC; assumption)) (by euclid_assumption "" (show c.onLine BC; assumption)) (by euclid_assumption "" (show a.onLine AB; assumption)) (by euclid_assumption "" (show b.onLine AB; assumption)) (by euclid_assumption "" (show d.onLine CD; assumption)) (by euclid_assumption "" (show c.onLine CD; assumption)) (by euclid_assumption "" (show d ≠ c; assumption)) (by euclid_assumption "" (show a.sameSide b CD; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine CD; assumption)) (by euclid_assumption "" (show a.onLine AC; assumption)) (by euclid_assumption "" (show c.onLine AC; assumption)) (by euclid_assumption "" (show a ≠ c; assumption)) (by euclid_assumption "" (show k.onLine AC; assumption)) (by euclid_assumption "" (show between a h d; assumption)) (by euclid_assumption "" (show e.onLine EF; assumption)) (by euclid_assumption "" (show k.onLine EF; assumption)) (by euclid_assumption "" (show e.onLine AB; assumption)) (by euclid_assumption "" (show h.onLine GH; assumption)) (by euclid_assumption "" (show k.onLine GH; assumption)) (by euclid_assumption "" (show h ≠ k; assumption)) (by euclid_assumption "" (show a.sameSide e GH; assumption)) (by euclid_assumption "" (show ¬AD.intersectsLine EF; assumption)) (by euclid_assumption "" (show ¬AB.intersectsLine GH; assumption)) (by euclid_assumption "" (show f.onLine EF; assumption)) (by euclid_assumption "" (show g.onLine BC; assumption)) (by euclid_assumption "" (show g.onLine GH; assumption)) (by euclid_assumption "" (show f.onLine CD; assumption)) (by euclid_assumption "" (show f ≠ c; assumption)) (by euclid_assumption "" (show k.sameSide g CD; assumption)) (by euclid_assumption "" (show ¬EF.intersectsLine BC; assumption)) (by euclid_assumption "" (show ¬GH.intersectsLine CD; assumption)))
  euclid_finish

end Elements.Book1
